### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by cinderblock** [PrimeEuler/odrive#1]
Hello

I'm starting to use ODrive for a project but I don't use python much. I'd rather use JavaScript (TypeScript). I'm trying to get your package to work but I see that it hasn't been updated in 14 months. Any pointers on what might need to be updated to get this to work?

**Comment by PrimeEuler** [comment]
Have you tried the tool made from this project? https://github.com/PrimeEuler/odrivetool 
There is also an html interface available here: https://primeeuler.github.io/odrive/viewer.html

**Comment by cinderblock** [comment]
I'm on firmware v0.5.1 which seems to have changed some things.

Yes, I've seen the tool. I'm using that project as an example for how to use this library.

**Comment by PrimeEuler** [comment]
I'll load up that firmware and see what is different. I'm sure at the very least the enumerations have changed.  Are you getting errors or just missing things?

**Comment by cinderblock** [comment]
```txt
pi@raspberrydrive:~/node $ node node_modules/odrivetool/odrivetool.js
 |- Read JSON Definition : 0% - ||______________________________||
'Fibre connected to ODrive on USB.'
 |- Read JSON Definition : 100% - ||##############################||
internal/buffer.js:67
    throw new ERR_OUT_OF_RANGE('value', range, value);
    ^

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -32768 and <= 32767. Received 39744
    at checkInt (internal/buffer.js:67:11)
    at writeU_Int16BE (internal/buffer.js:827:3)
    at Buffer.writeInt16BE (internal/buffer.js:889:10)
    at Duplex.Response (/home/pi/node/node_modules/@primeeuler/fibre/lib/fibre.js:116:29)
    at Duplex.emit (events.js:314:20)
    at Duplex.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:282:9)
    at Duplex.Readable.push (_stream_readable.js:221:10)
    at InEndpoint.<anonymous> (/home/pi/node/node_modules/@primeeuler/fibre/lib/usbbulk_transport.js:98:33) {
  code: 'ERR_OUT_OF_RANGE'
}
```

PS, I highly recommend adding a [`bin` field](https://docs.npmjs.com/files/package.json#bin) to your `package.json`.

**Comment by PrimeEuler** [comment]
The [fibre.js](https://github.com/PrimeEuler/fibre/blob/master/lib/fibre.js) implementation is for protocol version 1 and it looks like the [python](https://github.com/madcowswe/ODrive/blob/master/Firmware/fibre/python/fibre/protocol.py) code is still on version 1 however the last update mentioned the CRC calculation documentation. The code @ fibre.js:116:29  calls `calc_crc16(PROTOCOL_VERSION, operation.payload) )` so chances are my  calc_crc16 function needs updated. I should be able to get to this tomorrow and update with a bin field as well. 
Thanks!

**Comment by cinderblock** [comment]
Thank you! I'm looking forward to when JavaScript is the goto language for higher level robot programming. There are some lovely things about Python but JavaScript isn't going anywhere and I'd rather use one language everywhere.

Would you accept pull requests that add TypeScript support?

**Comment by PrimeEuler** [comment]
I'm with you. I love the non-blocking, event driven nature of JavaScript. We are even seeing it make its way on to microcontrollers like the ESP32 running [espruino](https://www.espruino.com/). I haven't ventured into TypeScript to much because to me its just another language that you can compile into JavaScript. That being said, the type casting templates that it brings to the table are a perfect fit for a project like this. I also want to refactor my code to mimic the [python](https://github.com/madcowswe/ODrive/tree/master/Firmware/fibre/python/fibre) libraries with hopes of adding it to the official odrive repository at some point. 

I'm working on upgrading my firmware to v0.5.1 but it appears the Odrive [docs](https://docs.odriverobotics.com/) site is down currently. v0.5.1 definitely changed a good bit according to the blog [post](https://discourse.odriverobotics.com/t/firmware-v0-5-1-release-candidate-feedback-thread/5210).

**Comment by cinderblock** [comment]
Yeah, I had that mentality about CoffeeScript. the utility of TS with rich strict typing and automatic code completion in editors, with inline docs, is really hard to beat.

Fortunately you can pretty easily just publish the TS types and JS separately so that people not using TS can easily use the package. They even get the inline documentation features in modern editors but write their whole program in JS. It's a really good melding of the two optimizations, imho.

Let me know if I can help port. I'm still very new to ODrive but this would be a great way to get my hands dirty if I have the time.

**Comment by PrimeEuler** [comment]
The new code has much more documentation and a nice yaml [interface definition](https://github.com/madcowswe/ODrive/blob/3c49b7f8caa6bebbae1de740109ddd5088e18b04/Firmware/odrive-interface.yaml). Its used to compile the new [enumerations](https://github.com/madcowswe/ODrive/blob/3c49b7f8caa6bebbae1de740109ddd5088e18b04/tools/odrive/enums.py). It should be fairly simple to use this to build the TypeScript interface declarations.

**Comment by PrimeEuler** [comment]
All help is welcome! Thanks!

**Comment by PrimeEuler** [comment]
Looks like the [interface generator ](https://github.com/madcowswe/ODrive/blob/3c49b7f8caa6bebbae1de740109ddd5088e18b04/Firmware/fibre/tools/interface_generator.py) uses JSON Schema to export the json firmware definitions. They are wanting to make the enumerations defined in the json firmware definitions eventually. This would allow us to compile the JavaScript interfaces across firmware versions from the single json file that is read from the Odrive when you first connect instead of external files.

**Comment by cinderblock** [comment]
Wait, does ODrive send the full interface description on startup? That's cool. I'd presumed it was just a version number and you had to go lookup your own types.

This unfortunately might make it less compatible with the strict typing of TypeScript...

**Comment by PrimeEuler** [comment]
yeah, the concept behind [Fibre](https://github.com/madcowswe/ODrive/tree/master/Firmware/fibre) object remoting allows for dynamic object definition as well as manipulation. The Odrive project doesn't allow you to modify the schema at runtime, so as not to damage the hardware, but it very well could.

**Comment by cinderblock** [comment]
Yeah, so I'm worried about making a good stable TypeScript API that supports the possible dynamic schema

**Comment by PrimeEuler** [comment]
If we used the [interface definition](https://github.com/madcowswe/ODrive/blob/3c49b7f8caa6bebbae1de740109ddd5088e18b04/Firmware/odrive-interface.yaml) instead of reading the JSON from the Odrive, it could be statically compiled from typescript. 
It seems like the current solution isn't quite complete because if you have to use the yaml file to figure out the enumerations, what is the point of having the JSON file loaded into the firmware on the device? Seems like putting a copy of the yaml file in the firmware would be the better approach.
Either way, I have the crc issues worked out in fibre.js and a new enum.json file as part of this project. I'll be publishing the new version tomorrow.

**Comment by PrimeEuler** [comment]
Just published all updates to the npm registry. Let me know if you have any issues.

**Comment by cinderblock** [comment]
Seems to work so far! thanks!
